# Generated by Django 5.1.2 on 2024-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0003_agentfeedback_buynow_payment_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bath_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bed_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
