# Generated by Django 5.1.2 on 2024-10-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0004_property_bath_no_property_bed_no_property_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='document',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='status',
            new_name='status_available',
        ),
    ]
