# Generated by Django 5.1.2 on 2024-10-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0005_rename_document_property_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='buynowProduct',
            new_name='buynowProperty',
        ),
    ]
