# Generated by Django 5.1.2 on 2024-10-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0006_rename_buynowproduct_payment_buynowproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentFeedback',
        ),
    ]
